import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "../styles/Home.module.css";
import MainVideo from "../components/BackgroundVideo/MainVideo";
import { useEffect, useRef } from "react";
import Presentation from "../components/Presentation/Presentation";
import Footer from "../components/Footer/Footer";
import ImagesWithShadow from "../components/ImagesWithShadow/ImagesWithShadow";

export default function Home() {
  const mainRef = useRef<HTMLDivElement | null>(null);

  return (
    <>
      <Head>
        <title>A.G.N Detailing</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <MainVideo />
        <ImagesWithShadow/>
        <Presentation />
        <Footer />
      </main>
    </>
  );
}
